INSERT INTO `anime`(`title`, `genre`, `synopsis`, `aired`, `ended`, `rating`)
VALUES ('Naruto',
'Aventure, Arts Martiaux',
"Dans le village de Konoha vit Naruto, un jeune garçon détesté et craint des villageois, du fait qu'il détient en lui Kyuubi (démon renard à neuf queues) d'une incroyable force, qui a tué un grand nombre de personnes. Le ninja le plus puissant de Konoha à l'époque, Minato Namikaze, a réussi à sceller ce démon dans le corps de Naruto. C'est ainsi que douze ans plus tard, Naruto rêve de devenir le plus grand Hokage de Konoha afin que tous le reconnaissent à sa juste valeur. Mais la route pour devenir Hokage est très longue.",
'1999/09/21',
'2014/11/10',
8.3),
('Naruto: Shippuden', 'Aventure, Arts Martiaux',
"Naruto est de retour !! Après deux ans et demi d'entraînement avec Jiraya, il retrouve ses camarades de l'Académie des ninja ainsi que ses professeurs de Konoha. Tous ont évolué, y compris les ninjas du village de Suna. Seul Kakashi, semble être resté fidèle à lui-même ! Hélas, les retrouvailles sont de courte durée. Gaara, devenu depuis peu Kazekage de son village, est menacé. Tout porte à croire que l'Akatsuki soit à l'origine de l'attaque.",
'2007/02/15',
'2017/03/23',
8.6),
('Boruto: Naruto Next Generations',
'Aventure, Arts Martiaux',
"Boruto est le fils de Naruto Uzumaki, le septième Hokage du village de Konoha, et célèbre ninja. Ayant toujours vécu dans l'ombre de son père, le garçon est décidé à le surpasser. Mais son entrée à l'académie des ninjas de Konoha va lui apprendre que devenir le meilleur ninja est plus difficile qu'il ne l'aurait cru.",
'2017/04/05',
null,
7.0)
